- name: Update cache
  ansible.builtin.dnf:
    update_cache: yes
- name: Update all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
- name: Autoremove unneeded packages
  ansible.builtin.dnf:
    autoremove: yes
- name: Blackbeard laugh
  command: echo "Zehahahaha"
